MyBlog.UI/Areas/Admin/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Entities.ORM.Concrete;
using MyBlog.UI.ApiService.Abstract;
using MyBlog.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.UI.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class BlogController : Controller
    {
        private readonly IBlogApiService _blogApiService;
        private readonly ICategoryApiService _categoryApiService;

        public BlogController(IBlogApiService blogApiService, ICategoryApiService categoryApiService)
        {
            _blogApiService = blogApiService;
            _categoryApiService = categoryApiService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _blogApiService.GetAll());
        }


        public IActionResult CreateBlog()
        {

            return View(new BlogsAddModel());
        }


        [HttpPost]
        public async Task<IActionResult> CreateBlog(BlogsAddModel model)
        {
            if (ModelState.IsValid)
            {
                await _blogApiService.CreateBlog(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        public async Task<IActionResult> UpdateBlog(int id)
        {
            var blog = await _blogApiService.GetOneBlog(id);



            return View(new BlogUpdate() { 
            ID=blog.ID,
            ContentTitle=blog.ContentTitle,
            ShortTitle=blog.ShortTitle,
            Title=blog.Title
            
            });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBlog(BlogUpdate model)
        {
            if (ModelState.IsValid)
            {
                model.AppUserID = 1;
                await _blogApiService.UpdateBlog(model);
                return RedirectToAction("Index");
            }


            return View(model);
        }

        public async Task<IActionResult> DeleteBlog(int id)
        {
            await _blogApiService.DeleteBlog(id);

            return RedirectToAction("Index");


        }

        public async Task<IActionResult> AssignCategory(int id)
        {
            var category =await _categoryApiService.GetAll();
            var blog = (await _blogApiService.GetAllCategory(id)).Select(i=>i.Title).ToList();
            TempData["BlogID"] = id;

            List<CategoryModel> categorymodel = new List<CategoryModel>();

            foreach (var item in categorymodel)
            {
                CategoryModel model = new CategoryModel();
                model.CategoryID = item.CategoryID;
                model.CategoryName = item.CategoryName;
                model.Exist = blog.Contains(item.CategoryName);
               

                categorymodel.Add(model);

            }

            return View(categorymodel);
        }

        [HttpPost]
        public async Task<IActionResult> AssignCategory(List<CategoryModel> model)
        {

            int id = (int)TempData["BlogID"];
            foreach (var item in model)
            {
                if (item.Exist)
                {
                    CategoryBlog categoryBlog = new CategoryBlog();
                    categoryBlog.BlogID = id;
                    categoryBlog.CategoryID = item.CategoryID;
                    await _blogApiService.AddCategoryBlog(categoryBlog);
                }

                else
                {
                    CategoryBlog categoryBlog = new CategoryBlog();
                    categoryBlog.BlogID = id;
                    categoryBlog.CategoryID = item.CategoryID;
                    await _blogApiService.RemoveCategoryBlogs(categoryBlog);
                }
            }

            return RedirectToAction("Index");

          


        }

    }
}

MyBlog.UI/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.DTO.DTO.CategoryDtos;
using MyBlog.UI.ApiService.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.UI.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryApiService _categoryApiService;

        public CategoryController(ICategoryApiService categoryApiService)
        {
            _categoryApiService = categoryApiService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryApiService.GetAll());
        }

        public IActionResult CreateCategory()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateCategory(CategoryAddUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                await _categoryApiService.CreateCategory(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> CategoryUpdate(int id)
        {
            var category = await _categoryApiService.GetByName(id);

            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> CategoryUpdate(CategoryAddUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                await _categoryApiService.UpdateCategory(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }
        public async Task<IActionResult> DeleteCategory(int id)
        {
            await _categoryApiService.DeleteCategory(id);

            return RedirectToAction("Index");
        }

    }
}

MyBlog.UI/Areas/Admin/Views/Blog/AssignCategory.cshtml
@model List<CategoryModel> 
@{
    ViewData["Title"] = "AssignCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<form action="AssignCategory" method="post">

    <div class="form-check">
        @for (int i = 0; i < Model.Count(); i++)
        {
            <input type="hidden" asp-for="@Model[i].CategoryID" />
            <input type="hidden" asp-for="@Model[i].CategoryName" />

            <input asp-for="@Model[i].Exist" type="checkbox" class="form-check-input" />
            <label asp-for="@Model[i].Exist" class="form-check-label">@Model[i].CategoryName</label>
        }

    </div>

    <button type="submit" class="btn btn-primary">Kaydet</button>



</form>

MyBlog.UI/Areas/Admin/Views/Blog/CreateBlog.cshtml
@model BlogsAddModel
@{
    ViewData["Title"] = "CreateBlog";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

@using (Html.BeginForm("CreateBlog", "Blog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="form-group">

        <label>Title</label>
        <input type="text" asp-for="Title" class="form-control" />


    </div>

    <div class="form-group">

        <label>Short Title</label>
        <input type="text" asp-for="ShortTitle" class="form-control" />


    </div>

    <div class="form-group">

        <label>Content Title</label>
        <textarea asp-for="ContentTitle"></textarea>


    </div>

    <div class="form-group">

        <label>Image</label>
        <input type="file" asp-for="Images" class="form-control" />


    </div>


    <button type="submit" class="btn btn-primary">Gönder</button>


}

@section Css{



    <link href="~/Trumbowyg-master/dist/ui/trumbowyg.css" rel="stylesheet" />
}

@section Javascript{

    <script src="~/Trumbowyg-master/dist/trumbowyg.js"></script>

    <script>

        $("#ContentTitle").trumbowyg();


    
    </script>

}

MyBlog.UI/Areas/Admin/Views/Blog/Index.cshtml
@model List<BlogListModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<table class="table table-bordered">

    <thead>

        <tr>
            <th>Content Title</th>
            <th>Short Title</th>
            <th>Title</th>

        </tr>

    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>

            <td>@item.ContentTitle</td>
            <td>@item.ShortTitle</td>
            <td>@item.Title</td>
            <td><a asp-action="UpdateCategory" asp-controller="Category" asp-route-id="@item.ID">Güncelle</a></td>
            <td>@Html.ActionLink("Sil", "DeleteBlog", "Blog", new { id = item.ID }, new { @class = "btn btn-danger" })</td>

            <td><a asp-action="AssignCategory" asp-controller="Blog" asp-route-id="@item.ID">Kategori Ata</a></td>
        </tr>
        }


    </tbody>



</table>

MyBlog.UI/Areas/Admin/Views/Blog/UpdateBlog.cshtml
@model BlogUpdate 
@{
    ViewData["Title"] = "UpdateBlog";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("UpdateBlog", "Blog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.HiddenFor(i=>i.ID)

    <div class="form-group">

        <label>Title</label>
        <input type="text" asp-for="Title" class="form-control" />


    </div>

    <div class="form-group">

        <label>Short Title</label>
        <input type="text" asp-for="ShortTitle" class="form-control" />


    </div>

    <div class="form-group">

        <label>Content Title</label>
        <textarea asp-for="ContentTitle"></textarea>


    </div>

    <div class="form-group">

        <label>Image</label>
        <input type="file" asp-for="Images" class="form-control" />


    </div>


    <button type="submit" class="btn btn-primary">Gönder</button>


}

@section Css{



    <link href="~/Trumbowyg-master/dist/ui/trumbowyg.css" rel="stylesheet" />
}

@section Javascript{

    <script src="~/Trumbowyg-master/dist/trumbowyg.js"></script>

    <script>

        $("#ContentTitle").trumbowyg();



    </script>

}